import { Newsreader } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import NavBar from "@/components/NavBar";

const newsreader = Newsreader({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "Aselsa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={newsreader.className}>
      <body>
        <Header />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
